### ISSUE TITLE
Error creating ReadPhilips node

### ISSUE THREAD

**Issue by GastaoCruz** [gpilab/philips-data-reader#5]
Creating a ReadPhilips node in the GPI fails some validation phase with the following error:

gpi.node:604 - ERROR - ReadPhilips: validate() failed.

Perhaps I have installed this incorrectly. Any help is appreciated.

**Comment by aganders3** [comment]
Hi Gastao,

Can you provide some more information? Please let us know the platform/OS you're using, the version of GPI, and the version of the ReadPhilips node.

Does this happen right when you instantiate the node, or after you choose a file to read?

Thanks!

**Comment by GastaoCruz** [comment]
Hi Andrew,

I'm running GPI release 1.0.0 and the ReadPhilips from January this year (i.e., this one -> https://github.com/gpilab/philips-data-reader/releases/tag/4) on an Ubuntu OS. The error appears when the node is created (before the any file is selected).

Thanks,
Gastao

**Comment by aganders3** [comment]
Hmm...as far as I know we haven't run into that issue. I'd try release 5 (https://github.com/gpilab/philips-data-reader/releases/tag/5) and see if that fixes it. I'll ask around here in case anyone else has experienced this, and try to reproduce the bug on a fresh install in my Ubuntu VM.

**Comment by aganders3** [comment]
OK, I can reproduce this in my VM running GPI 1.0.0 and 1.0.2 with release 5 of the ReadPhilips. I'll look into this further and post an update here.

**Comment by aganders3** [comment]
Thanks for the report, Gastao. We don't always spot the bugs in the binary releases since most of us have the source checkout, so we appreciate the bug report!

I just published a new release (version 6, https://github.com/gpilab/philips-data-reader/releases/tag/6) with binaries for Mac OS X and Linux. I tested it and it is working for me on Ubuntu. Please give it a shot and let me know if it fixes your problem.

**Comment by GastaoCruz** [comment]
Thanks for the quick reply, Ashley. I've been away but I will test the new build as soon as possible.

Many thanks,
Gastao

**Comment by GastaoCruz** [comment]
Hi Ashley,

Thanks a lot for your help. I have updated to version 6, but unfortunately the ReadPhilips node still fails the validate() function. Is there anything I can do on my end to try to debug this problem?

Best,
Gastao

**Comment by aganders3** [comment]
Unfortunately since we're unable to distribute the source code for this node, there's not a lot of other debugging information we can get for you. However, we came up with two scenarios that would present with these symptoms, both related to how (or rather, whether or not) the library is installed.

1) The library is installed with the incorrect directory name. The top library directory must be called `philips`. This directory should be installed in `~/gpi` or else in a location specified in your `~/.gpirc` config file.
```
~/gpi/philips
├── __init__.pyc
└── fileIO
    ├── GPI
    │   └── ReadPhilips_GPI.pyc
    ├── __init__.pyc
    ├── readMira.pyc
    ├── readPhilips.so
    └── readPhilipsExports.pyc
```

2) How are you instantiating the node? If you are dropping the `ReadPhilips_GPI.pyc` file directly on the canvas, you will get this error. You need to install the library (as above) and instantiate the node by right-clicking on the GPI canvas.

Hopefully this helps. Otherwise can you please describe how you have installed the package, and give a description of the current state (e.g. where the files are, etc.).

Thanks for your help and patience, and sorry you're having issues with this! We'll work on smoothing out the installation as much as possible.

**Comment by GastaoCruz** [comment]
Hi Ashley,

The library is indeed installed in a ~/gpi directory:
![image](https://cloud.githubusercontent.com/assets/3919329/16190262/59b518de-36d6-11e6-8416-b38cf010e650.png)

And the error I mentioned before does happen when I instantiate a node by right-lick -> drop down menu -> philips -> fileIO -> ReadPhilips:
![image](https://cloud.githubusercontent.com/assets/3919329/16190617/269da748-36d8-11e6-8fa2-164689cd8d5c.png)

I was not the one that installed the package, but I know these instructions were followed carefully:

1. create a gpi directory in your home directory ~/gpi
2. unzip the ReadPhilips_<date>.zip directory under ~/gpi
3. run the make in the ~/gpi/philips directory: gpi_make --all

If there's anything else I can help with please let me know.
Best,
Gastao

**Comment by aganders3** [comment]
Thanks again, Gastao.

By `~/gpi` we actually mean to install it within a `gpi` directory in your home directory (in *nix environments, the tilde `~` is a shortcut for your home directory). In your case it looks like this should be `/home/gc13/gpi`. You shouldn't need to put anything into the `/opt/gpi` folder where you have chosen to install GPI. Still, I'm not sure this will fix the problem you are experiencing. You should move the `philips` folder (or re-install it) into `/home/gc13/gpi`.

Can you please also post the contents of the file `/home/gc13/.gpirc` and `/home/gc13/gpi/philips/VERSION.`? You can post them as a gist (gist.github.com) or on a paste-server like sprunge.io.

Finally, you can try updating the GPI framework itself. The auto-updater is a big buggy, but it should work if you go to Help -> Check for updates...

Thanks!

**Comment by GastaoCruz** [comment]
Hi Ashley,

I misunderstood the notation for home directory. I have moved the philips instalation to the home folder (indeed /home/gc13/gpi). I have tried the auto-updater which did update the core nodes, but the ReadPhilips is still not working properly.

In the .gpirc file I have just given the paths to the node libraries. I have uploaded the contents of these files to gist as suggested: https://gist.github.com/GastaoCruz/48af180019f744ed34d0b8b2cd273d0e

I half-suspect this error is due to a lapse on my part. If there's anymore debug material you need please let me know.

Best,
Gastao

**Comment by aganders3** [comment]
I was finally able to reproduce this in my VM. I think it's a problem in your `.gpirc` file, though no fault of your own. This seems to only be a problem in the binary release so I don't think our instructions were clear enough. I will add a note to the installation instructions regarding this.

Please change `LIB_DIRS` in your `.gpirc` from

    LIB_DIRS = /home/gc13/gpi/philips/:/opt/gpi/lib/python3.5/site-packages/gpi/node-libs/

to

    LIB_DIRS = /home/gc13/gpi:/opt/gpi/lib/python3.5/site-packages/gpi/node-libs

Alternatively, if you don't plan to install node libraries in any other location this is actually the default `LIB_DIRS` path, so you could just comment that line out entirely.

In my Ubuntu VM, this seems to fix the problem. Hopefully it works for you!

@nckz any idea why this would cause this issue? I assume it's related to the path of the library, which must be frozen somehow in the compiled version.

**Comment by GastaoCruz** [comment]
Hi Ashley,

The ReadPhilips note has been instantiated correctly.

Thanks!
Gastao

**Comment by aganders3** [comment]
Great! I'm closing this and will take a look at clarifying the installation instructions.
